CREATE TABLE DEPLOY
(
    DEPLOY_ID    NUMBER(19)     NOT NULL,
    DEPLOY_NAME  NVARCHAR2(255) NOT NULL,
    DEPLOY_TYPE  NUMBER(11)     NOT NULL,
    FILE_NAME    NVARCHAR2(255) NOT NULL,
    FILE_SIZE    NUMBER(19)     NOT NULL,
    CREATOR      NVARCHAR2(255) NULL,
    CREATED_DATE TIMESTAMP      NULL,
    CONSTRAINT DEPLOY_PK PRIMARY KEY (DEPLOY_ID)
);

CREATE TABLE DEPLOY_TRANSFER
(
    DEPLOY_TRANSFER_ID      NUMBER(19)     NOT NULL,
    DEPLOY_ID               NUMBER(19)     NOT NULL,
    BANDWIDTH_KBPS          NUMBER(11)     NULL,
    USE_COMPRESS            NUMBER(1)      NULL,
    MULTICAST_GROUP_ADDRESS NVARCHAR2(15)  NULL,
    MULTICAST_GROUP_PORT    NUMBER(11)     NULL,
    STATUS                  NVARCHAR2(10)  NULL,
    REPEAT_COUNT            NUMBER(11)     NULL,
    TRANSFER_COUNT          NUMBER(11)     NULL,
    REACTIVE_CLIENT_COUNT   NUMBER(11)     NULL,
    FINISHED_DATE           TIMESTAMP      NULL,
    CREATOR                 NVARCHAR2(255) NULL,
    CREATED_DATE            TIMESTAMP      NULL,
    EXECUTE_INSTALL_DATE    TIMESTAMP      NULL,
    RECEIVE_STATUS          CLOB           NULL,
    CONSTRAINT DEPLOY_TRANSFER_PK PRIMARY KEY (DEPLOY_TRANSFER_ID)
);
CREATE INDEX FKIDX_DEPLOY_TRANSFER1 ON DEPLOY_TRANSFER (DEPLOY_ID);
CREATE INDEX IDX_DEPLOY_TRANSFER1 ON DEPLOY_TRANSFER (DEPLOY_ID, DEPLOY_TRANSFER_ID);


CREATE TABLE DEPLOY_TRANSFER_HISTORY
(
    DEPLOY_TRANSFER_HISTORY_ID NUMBER(19) NOT NULL,
    DEPLOY_TRANSFER_ID         NUMBER(19) NOT NULL,
    REPEAT_POS                 NUMBER(11) NULL,
    SEQ                        NUMBER(11) NULL,
    SENT_DATE                  TIMESTAMP  NULL,
    CHUNK_SIZE_ORG             NUMBER(19) NULL,
    CHUNK_SIZE_SENT            NUMBER(19) NULL,
    USE_COMPRESS               NUMBER(1)  NULL,
    LOSS_COUNT                 NUMBER(11) NULL,
    CONSTRAINT DEPLOY_TRANSFER_HISTORY_PK PRIMARY KEY (DEPLOY_TRANSFER_HISTORY_ID)
);
CREATE INDEX FKIDX_DEPLOY_TRANSFER_HISTORY ON DEPLOY_TRANSFER_HISTORY (DEPLOY_TRANSFER_ID);
CREATE INDEX IDX_DEPLOY_TRANSFER_HISTORY1 ON DEPLOY_TRANSFER_HISTORY (DEPLOY_TRANSFER_ID, DEPLOY_TRANSFER_HISTORY_ID);


